/*
 * This file is generated by jOOQ.
 */
package com.testjooq.tables.records;


import com.testjooq.tables.Account;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends TableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooqtest.account.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooqtest.account.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooqtest.account.details</code>.
     */
    public void setDetails(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooqtest.account.details</code>.
     */
    public String getDetails() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Integer id, String details) {
        super(Account.ACCOUNT);

        setId(id);
        setDetails(details);
        resetChangedOnNotNull();
    }
}
