/*
 * This file is generated by jOOQ.
 */
package com.testjooq.tables.records;


import com.testjooq.tables.Object;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ObjectRecord extends TableRecordImpl<ObjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jooqtest.object.obj_id</code>.
     */
    public void setObjId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooqtest.object.obj_id</code>.
     */
    public Integer getObjId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooqtest.object.details</code>.
     */
    public void setDetails(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooqtest.object.details</code>.
     */
    public String getDetails() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjectRecord
     */
    public ObjectRecord() {
        super(Object.OBJECT);
    }

    /**
     * Create a detached, initialised ObjectRecord
     */
    public ObjectRecord(Integer objId, String details) {
        super(Object.OBJECT);

        setObjId(objId);
        setDetails(details);
        resetChangedOnNotNull();
    }
}
