/*
 * This file is generated by jOOQ.
 */
package com.testjooq;


import com.testjooq.tables.Account;
import com.testjooq.tables.Object;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Jooqtest extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooqtest</code>
     */
    public static final Jooqtest JOOQTEST = new Jooqtest();

    /**
     * The table <code>jooqtest.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>jooqtest.object</code>.
     */
    public final Object OBJECT = Object.OBJECT;

    /**
     * No further instances allowed
     */
    private Jooqtest() {
        super("jooqtest", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            Object.OBJECT
        );
    }
}
