/*
 * This file is generated by jOOQ.
 */
package com.testjooq;


import com.testjooq.tables.Account;
import com.testjooq.tables.Object;


/**
 * Convenience access to all tables in jooqtest.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>jooqtest.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>jooqtest.object</code>.
     */
    public static final Object OBJECT = Object.OBJECT;
}
